version: '3.8'

services:
  db:
    image: postgres
    container_name: owlrangenotes_db
    restart: always
    ports:
      - 54320:5432
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
